spring:
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY:sk-25c24c7ecacf41dd9da7471d89d32c15}
      chat:
        options:
          model: qwen-plus
  application:
    name: loveAgent
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com/example/loveagent/controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn



